 Q.How do you assign a random number to a variable in Python?
 
 Assigning a Random Number to a Variable in Python  
1. Using the random module:
   
   import random
   num = random.randint(1, 100)  # Assigns a random integer between 1 and 100
   print(num)
   
2. Using random.uniform() for floating-point numbers: 
   
   num = random.uniform(1, 100)  # Assigns a random float between 1 and 100
   print(num)
   
3. Using `random.random()` for a random float between 0 and 1:
   num = random.random()  # Assigns a random float between 0 and 1
   print(num)



Q.What is the use of os module in python? 


 Use of `os` Module in Python  
The `os` module provides functions for interacting with the operating system.  

1. File and Directory Management: 
   - `os.mkdir('new_folder')` → Creates a new directory  
   - `os.listdir()` → Lists files and directories in the current directory  
   - `os.remove('file.txt')` → Deletes a file  

2. Path Operations:  
   - `os.getcwd()` → Returns the current working directory  
   - `os.path.join('folder', 'file.txt')` → Joins paths correctly for different OS  

3. System Operations:  
   - `os.system('ls')` → Executes a system command (e.g., listing files in Linux)  
   - `os.getenv('HOME')` → Retrieves environment variables  
   

Q.Explain how matrix multiplications are done using NumPy arrays.

Matrix Multiplication using NumPy Arrays
Matrix multiplication in NumPy can be performed using:
1. The `dot()` function  
2. The `@` operator  
3. The `matmul()` function  

Example:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

 Method 1: Using dot()
result1 = np.dot(A, B)

 Method 2: Using @ operator
result2 = A @ B

 Method 3: Using matmul()
result3 = np.matmul(A, B)

print(result1)

Q.How to plot two or more lines on the same plot with suitable legends, labels, and a title.

 Plotting Multiple Lines on a Single Graph
Using Matplotlib, multiple lines can be plotted on a single graph:

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y1 = [2, 4, 6, 8, 10]
y2 = [1, 3, 5, 7, 9]

plt.plot(x, y1, label="Line 1", color="red", linestyle="dashed")
plt.plot(x, y2, label="Line 2", color="blue", linestyle="solid")

plt.xlabel("X-axis Label")
plt.ylabel("Y-axis Label")
plt.title("Multiple Lines Plot")
plt.legend()
plt.show()

Q.Write a Python code that checks to see, if a file with the given pathname exists on the disk, before attempting to open a file for input.  

1. Using `os.path.exists()`
   import os

   file_path = "example.txt"

   if os.path.exists(file_path):
       with open(file_path, "r") as file:
           content = file.read()
           print(content)
   else:
       print("File does not exist.")


2. Using `pathlib` (Recommended for Modern Python Versions)
   from pathlib import Path

   file_path = Path("example.txt")

   if file_path.is_file():
       with file_path.open("r") as file:
           content = file.read()
           print(content)
   else:
       print("File does not exist.")
   

3.Using `try-except` Block
   try:
       with open("example.txt", "r") as file:
           content = file.read()
           print(content)
   except FileNotFoundError:
       print("File does not exist.")

Q.What is Flask in Python? What are its basic components?

Flask is a lightweight and micro web framework in Python used for building web applications. It is designed to be simple, yet flexible, making it a popular choice for small to medium-sized web projects.

Basic Components of Flask 

1. Flask Application Object
   - Created using `Flask(__name__)` to define the web application.  
   from flask import Flask  
   app = Flask(__name__)  


2. Routes & Views 
   - Defines URL routes and their associated view functions.  
   @app.route("/")  
   def home():  
       return "Hello, Flask!"  
   

3. Templates & Jinja2 
   - Supports HTML templates using Jinja2 templating engine.  
   <!-- example.html -->
   <h1>Hello, {{ name }}!</h1>
   

4. Request Handling 
   - Handles GET and POST requests.  
  
   from flask import request  

   @app.route("/submit", methods=["POST"])  
   def submit():  
       data = request.form["name"]  
       return f"Hello, {data}!"
   

5. Flask Extensions 
   - Includes extensions for databases, authentication, and more (e.g., Flask-SQLAlchemy, Flask-Login).  

6. Development Server  
   - Run the application using:  
  
   if __name__ == "__main__":  
       app.run(debug=True)  
   

Q.write the output of the following python code
import numpy as np 
import numpy as np 
arr1 = np.arange(6).reshape((3, 2)) 
arr2 = np.arange(6).reshape((3,2)) 
arr3 = arr1 + arr2[0].reshape((1, 2))  
print(arr3) 


1. `arr1 = np.arange(6).reshape((3, 2))`  
   
   [[0 1]
    [2 3]
    [4 5]]
   
2. `arr2 = np.arange(6).reshape((3, 2))`  
   
   [[0 1]
    [2 3]
    [4 5]]
   
3. `arr2[0].reshape((1,2))` 
   [[0 1]]
   
4. addition
   [[0+0  1+1]  =>  [0  2]
    [2+0  3+1]  =>  [2  4]
    [4+0  5+1]] =>  [4  6]
o/p:
[[0 2]
 [2 4]
 [4 6]]


Q.What is the difference between loc and iloc in pandas DataFrame.

loc is label-based indexing, meaning it selects data using row and column labels. It includes the end index when slicing.

Example: df.loc[2, 'Name'] selects the value from row index 2 and column 'Name'.

iloc is integer-based indexing, meaning it selects data using numerical positions. It excludes the end index when slicing.

Example: df.iloc[2, 1] selects the value from row index 2 and column index 


Q. Explain the attributes of an ndarray object.   

An `ndarray` (N-dimensional array) is the core data structure in NumPy. It has several attributes that provide information about the array:  

1. `ndarray.shape`
   - Returns a tuple representing the dimensions of the array.  
   - Example: `arr.shape` for a 3x2 array → `(3, 2)`.  

2. `ndarray.ndim` 
   - Returns the number of dimensions (axes) in the array.  
   - Example: A 2D array has `ndim = 2`.  

3. `ndarray.size` 
   - Returns the total number of elements in the array.  
   - Example: A 3x2 array has `size = 6`.  

4. `ndarray.dtype`
   - Specifies the data type of the elements in the array.  
   - Example: `int32`, `float64`, etc.  

5. `ndarray.itemsize`  
   - Returns the size (in bytes) of each element in the array.  
   - Example: `int32` elements have an item size of 4 bytes.  

6. `ndarray.data` 
   - Returns a buffer containing the actual array elements in memory.  

Q. Explain the use of flask in web development. write in structured format

Flask is a lightweight Python web framework used for building web applications. It provides tools and libraries to develop web services efficiently.  

1. Key Features of Flask 
- Lightweight and Minimalistic – Uses a simple structure without enforcing project layouts.  
- Built-in Development Server – Helps test applications without an external web server.  
- Jinja2 Templating – Allows dynamic HTML rendering.  
- Integrated Routing System – Maps URLs to Python functions easily.  
- Support for Extensions – Can integrate with databases, authentication, and APIs.  

2. Basic Flask Web Application Example

from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return "Hello, Flask!"

if __name__ == "__main__":
    app.run(debug=True)

- `Flask(__name__)` – Creates an instance of the Flask application.  
- `@app.route("/")`– Maps the home page (`/`) to a function.  
- `app.run(debug=True)` – Runs the server with debug mode enabled.  

3. Common Uses of Flask 
- Developing APIs – RESTful web services for mobile and web applications.  
- Building Web Applications – Used in dashboards, blogs, and business applications.  
- Machine Learning Deployment – Hosts ML models as APIs for real-time inference.  


Q.Explain the different ways by which numpy arrays are created.


1. Using `np.array()`
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
Creates an array from a list.

2. Using `np.arange()`
arr = np.arange(1, 10, 2)
print(arr)
Creates an array with a range of numbers (start, stop, step).

3. Using `np.zeros()` and `np.ones()`

zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))
print(zeros_arr)
print(ones_arr)
Creates arrays filled with zeros or ones.
4. Using `np.linspace()`

arr = np.linspace(0, 1, 5)
print(arr)
Creates an array with evenly spaced values between start and stop.

5. Using `np.random` (Random Arrays)
rand_arr = np.random.rand(3, 3)
print(rand_arr)
Creates a random array of shape (3,3) with values between 0 and 1.

6. Using `np.eye()`
identity_matrix = np.eye(3)
print(identity_matrix)
Creates an identity matrix of size 3x3.


In [ ]:
Q.How does isnull() function in Pandas help in handling missing values?

The isnull() function in Pandas is used to detect missing or NaN (Not a Number) values in a DataFrame or Series. It helps in data cleaning and preprocessing.

Key Features of isnull()
Identifies Missing Values: Returns True for missing values and False for non-missing values.

Works on DataFrames & Series: Can be applied to both rows and columns.

Used for Data Cleaning: Helps filter or replace missing data.